新增测试类

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -14,4 +14,9 @@ jobs:
           architecture: 'x64'
           cache: maven
       - name: Build with Maven
-        run: mvn test -Dtest=HZTest
+        run: mvn --batch-mode --update-snapshots verify
+      - uses: actions/upload-artifact@v2  # upload test results
+          if: success() || failure()        # run this step even if previous step failed
+          with:
+            name: test-results
+            path: jest-junit.xml
